---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 3.1 Get Absolute Path to grub.cfg
    command: readlink -f /boot/grub/grub.cfg
    register: readlink
    changed_when: false
    always_run: yes
    sudo: yes
    tags:
      - scored
      - section3.1
      
  - name: 3.1 Set User/Group Owner on bootloader config (Scored)
    file: >
      path={{ readlink.stdout }}
      owner=root
      group=root
    sudo: yes
    tags:
      - scored
      - section3.1
      
  - name: 3.2 Get Absolute Path to grub.cfg
    command: readlink -f /boot/grub/grub.cfg
    register: readlink
    changed_when: false
    always_run: yes
    sudo: yes
    tags:
      - scored
      - section3.2

  - name: 3.2 Set Permissions on bootloader config (Scored)
    file: >
      path={{ readlink.stdout }}
      mode=0400
    sudo: yes
    tags:
      - scored 
      - section3.2

  - name: 3.3 Set Boot Loader Password (Scored)
    debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
    tags:
      - scored
      - section3.3
      
  - name: 3.4 Require Authentication for Single-User Mode (Scored)
    debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
    tags:
      - scored
      - section3.4
